# Enable broken link checking in Netlify CI
[[plugins]]
package = "netlify-plugin-checklinks"
    [plugins.inputs]
    entryPoints = [
        "*.html",
    ]

    recursive = true
    pretty = true
    checkExternal = false

# These first rules are a bit fiddly -- we explicitly redirect URLs that we know should
# point to the Redux docs, rather than redirecting to `/`, then to `/redirect-to-redux-site.html`,
# which ends up breaking things on the Redux site side.
[[redirects]]
    from = "/docs/guide/*"
    to = "/redirect-to-redux-site.html#!docs/guide/:splat"
    # We may use this path for a new guidebook.
    status = 302

[[redirects]]
    from = "/docs/tutorials/*"
    to = "/redirect-to-redux-site.html#!docs/tutorials/:splat"
    # Holding open the possibility of tutorials too.
    status = 302

[[redirects]]
    from = "/docs/create-new-app/"
    to = "/redirect-to-redux-site.html#!docs/create-new-app/"
    status = 302

[[redirects]]
    from = "/resources/happ-bundle/"
    to = "/redirect-to-redux-site.html#!docs/resources/happ-bundle/"
    # There will eventually be a new hApp bundle format that will get documented,
    # and I intend to put it under `/references`.
    status = 302

# Some of the core concepts' titles and URLs have changed,
# but fortunately they map to new core concepts (sometimes roughly, sometimes exactly)
# so let's redirect them.
[[redirects]]
    from = "/docs/concepts/3_private_data/"
    to = "/concepts/3_source_chain/"
    status = 301

[[redirects]]
    from = "/docs/concepts/4_public_data_on_the_dht/"
    to = "/concepts/4_dht/"
    status = 301

[[redirects]]
    from = "/docs/concepts/5_linking_data_together/"
    to = "/concepts/5_links_anchors/"
    status = 301

[[redirects]]
    from = "/docs/concepts/6_modifying_and_deleting_data/"
    to = "/concepts/6_crud_actions/"
    status = 301

[[redirects]]
    from = "/docs/concepts/8_node_to_node_messaging/"
    to = "/concepts/8_calls_capabilities/"
    status = 301

# Once upon a time, we had a landing page and all the actual docs were in /docs.
[[redirects]]
    from = "/docs/*"
    to = "/:splat"
    status = 301

# Super old install URL; used to be incorrectly linked from the blog's CTAs.
[[redirects]]
    from = "/start.html"
    to = "/quick-start/"
    status = 301

# This is just for the nix guide, which is now called the advanced install guide.
[[redirects]]
    from = "/docs/nix/"
    to = "/install-advanced/"
    status = 301

# The rrDHT paper got finalised, so let's redirect to the final copy.
[[redirects]]
    from = "/assets/files/RRDHT-draft-Nov-2019.pdf"
    to = "/assets/files/RRDHT-whitepaper-final.pdf"
    status = 301
    
# The quick start guide used to live at /install/
[[redirects]]
    from = "/install/"
    to = "/quick-start/"
    status = 301
    
# Glossary has been moved to the references path.
[[redirects]]
    from = "/glossary/"
    to = "/references/glossary/"
    status = 301

# The front page for the core concepts has been removed.
[[redirects]]
    from = "/concepts/"
    to = "/concepts/1_the_basics/"
    # Keeping this as a 302 in case we decide we want a front page again.
    status = 302

# This comment does absolutely nothing and can be deleted.
