(function() {var implementors = {};
implementors["holochain_cas_implementations"] = [{text:"impl <a class=\"trait\" href=\"riker/actor/actor/trait.Actor.html\" title=\"trait riker::actor::actor::Actor\">Actor</a> for <a class=\"struct\" href=\"holochain_cas_implementations/cas/file/actor/struct.FilesystemStorageActor.html\" title=\"struct holochain_cas_implementations::cas::file::actor::FilesystemStorageActor\">FilesystemStorageActor</a>",synthetic:false,types:["holochain_cas_implementations::cas::file::actor::FilesystemStorageActor"]},{text:"impl <a class=\"trait\" href=\"riker/actor/actor/trait.Actor.html\" title=\"trait riker::actor::actor::Actor\">Actor</a> for <a class=\"struct\" href=\"holochain_cas_implementations/eav/file/actor/struct.EavFileStorageActor.html\" title=\"struct holochain_cas_implementations::eav::file::actor::EavFileStorageActor\">EavFileStorageActor</a>",synthetic:false,types:["holochain_cas_implementations::eav::file::actor::EavFileStorageActor"]},{text:"impl <a class=\"trait\" href=\"riker/actor/actor/trait.Actor.html\" title=\"trait riker::actor::actor::Actor\">Actor</a> for <a class=\"struct\" href=\"holochain_cas_implementations/eav/memory/actor/struct.EavMemoryStorageActor.html\" title=\"struct holochain_cas_implementations::eav::memory::actor::EavMemoryStorageActor\">EavMemoryStorageActor</a>",synthetic:false,types:["holochain_cas_implementations::eav::memory::actor::EavMemoryStorageActor"]},];
implementors["riker_deadletter"] = [{text:"impl&lt;Msg:&nbsp;<a class=\"trait\" href=\"riker/protocol/trait.Message.html\" title=\"trait riker::protocol::Message\">Message</a>&gt; <a class=\"trait\" href=\"riker/actor/actor/trait.Actor.html\" title=\"trait riker::actor::actor::Actor\">Actor</a> for <a class=\"struct\" href=\"riker_deadletter/struct.DeadLettersActor.html\" title=\"struct riker_deadletter::DeadLettersActor\">DeadLettersActor</a>&lt;Msg&gt;",synthetic:false,types:["riker_deadletter::DeadLettersActor"]},];
implementors["riker_log"] = [{text:"impl&lt;Msg&gt; <a class=\"trait\" href=\"riker/actor/actor/trait.Actor.html\" title=\"trait riker::actor::actor::Actor\">Actor</a> for <a class=\"struct\" href=\"riker_log/struct.SimpleLogger.html\" title=\"struct riker_log::SimpleLogger\">SimpleLogger</a>&lt;Msg&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;Msg: <a class=\"trait\" href=\"riker/protocol/trait.Message.html\" title=\"trait riker::protocol::Message\">Message</a>,&nbsp;</span>",synthetic:false,types:["riker_log::SimpleLogger"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
