(function() {var implementors = {};
implementors["holochain_core"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/future/future/trait.Future.html\" title=\"trait core::future::future::Future\">Future</a> for <a class=\"struct\" href=\"holochain_core/agent/actions/commit/struct.CommitFuture.html\" title=\"struct holochain_core::agent::actions::commit::CommitFuture\">CommitFuture</a>",synthetic:false,types:["holochain_core::agent::actions::commit::CommitFuture"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/future/future/trait.Future.html\" title=\"trait core::future::future::Future\">Future</a> for <a class=\"struct\" href=\"holochain_core/dht/actions/add_link/struct.AddLinkFuture.html\" title=\"struct holochain_core::dht::actions::add_link::AddLinkFuture\">AddLinkFuture</a>",synthetic:false,types:["holochain_core::dht::actions::add_link::AddLinkFuture"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/future/future/trait.Future.html\" title=\"trait core::future::future::Future\">Future</a> for <a class=\"struct\" href=\"holochain_core/nucleus/actions/build_validation_package/struct.ValidationPackageFuture.html\" title=\"struct holochain_core::nucleus::actions::build_validation_package::ValidationPackageFuture\">ValidationPackageFuture</a>",synthetic:false,types:["holochain_core::nucleus::actions::build_validation_package::ValidationPackageFuture"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/future/future/trait.Future.html\" title=\"trait core::future::future::Future\">Future</a> for <a class=\"struct\" href=\"holochain_core/nucleus/actions/initialize/struct.InitializationFuture.html\" title=\"struct holochain_core::nucleus::actions::initialize::InitializationFuture\">InitializationFuture</a>",synthetic:false,types:["holochain_core::nucleus::actions::initialize::InitializationFuture"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/future/future/trait.Future.html\" title=\"trait core::future::future::Future\">Future</a> for <a class=\"struct\" href=\"holochain_core/nucleus/actions/validate/struct.ValidationFuture.html\" title=\"struct holochain_core::nucleus::actions::validate::ValidationFuture\">ValidationFuture</a>",synthetic:false,types:["holochain_core::nucleus::actions::validate::ValidationFuture"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
