var ALIASES = {};
ALIASES["hdk"] = {};
ALIASES["holochain_cas_implementations"] = {};
ALIASES["holochain_common"] = {};
ALIASES["holochain_core_types"] = {};
ALIASES["holochain_core_types_derive"] = {};
ALIASES["holochain_dna_c_binding"] = {};
ALIASES["holochain_net"] = {};
ALIASES["holochain_wasm_utils"] = {};
