(function() {var implementors = {};
implementors["holochain_core"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/str/trait.FromStr.html\" title=\"trait core::str::FromStr\">FromStr</a> for <a class=\"enum\" href=\"holochain_core/nucleus/ribosome/api/enum.ZomeApiFunction.html\" title=\"enum holochain_core::nucleus::ribosome::api::ZomeApiFunction\">ZomeApiFunction</a>",synthetic:false,types:["holochain_core::nucleus::ribosome::api::ZomeApiFunction"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/str/trait.FromStr.html\" title=\"trait core::str::FromStr\">FromStr</a> for <a class=\"enum\" href=\"holochain_core/nucleus/ribosome/callback/enum.Callback.html\" title=\"enum holochain_core::nucleus::ribosome::callback::Callback\">Callback</a>",synthetic:false,types:["holochain_core::nucleus::ribosome::callback::Callback"]},];
implementors["holochain_core_types"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/str/trait.FromStr.html\" title=\"trait core::str::FromStr\">FromStr</a> for <a class=\"enum\" href=\"holochain_core_types/entry/entry_type/enum.EntryType.html\" title=\"enum holochain_core_types::entry::entry_type::EntryType\">EntryType</a>",synthetic:false,types:["holochain_core_types::entry::entry_type::EntryType"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/str/trait.FromStr.html\" title=\"trait core::str::FromStr\">FromStr</a> for <a class=\"enum\" href=\"holochain_core_types/error/enum.RibosomeReturnCode.html\" title=\"enum holochain_core_types::error::RibosomeReturnCode\">RibosomeReturnCode</a>",synthetic:false,types:["holochain_core_types::error::ribosome_error::RibosomeReturnCode"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/str/trait.FromStr.html\" title=\"trait core::str::FromStr\">FromStr</a> for <a class=\"enum\" href=\"holochain_core_types/error/enum.RibosomeErrorCode.html\" title=\"enum holochain_core_types::error::RibosomeErrorCode\">RibosomeErrorCode</a>",synthetic:false,types:["holochain_core_types::error::ribosome_error::RibosomeErrorCode"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/str/trait.FromStr.html\" title=\"trait core::str::FromStr\">FromStr</a> for <a class=\"enum\" href=\"holochain_core_types/dna/zome/capabilities/enum.ReservedCapabilityNames.html\" title=\"enum holochain_core_types::dna::zome::capabilities::ReservedCapabilityNames\">ReservedCapabilityNames</a>",synthetic:false,types:["holochain_core_types::dna::zome::capabilities::ReservedCapabilityNames"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
