(function() {var implementors = {};
implementors["hdk"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"hdk/api/struct.GetEntryMask.html\" title=\"struct hdk::api::GetEntryMask\">GetEntryMask</a>",synthetic:false,types:["hdk::api::GetEntryMask"]},];
implementors["holochain_core_types"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"holochain_core_types/crud_status/enum.CrudStatus.html\" title=\"enum holochain_core_types::crud_status::CrudStatus\">CrudStatus</a>",synthetic:false,types:["holochain_core_types::crud_status::CrudStatus"]},];
implementors["holochain_wasm_utils"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"holochain_wasm_utils/memory/allocation/struct.Offset.html\" title=\"struct holochain_wasm_utils::memory::allocation::Offset\">Offset</a>",synthetic:false,types:["holochain_wasm_utils::memory::allocation::Offset"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"holochain_wasm_utils/memory/allocation/struct.Length.html\" title=\"struct holochain_wasm_utils::memory::allocation::Length\">Length</a>",synthetic:false,types:["holochain_wasm_utils::memory::allocation::Length"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"holochain_wasm_utils/memory/allocation/struct.WasmAllocation.html\" title=\"struct holochain_wasm_utils::memory::allocation::WasmAllocation\">WasmAllocation</a>",synthetic:false,types:["holochain_wasm_utils::memory::allocation::WasmAllocation"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"holochain_wasm_utils/memory/stack/struct.Top.html\" title=\"struct holochain_wasm_utils::memory::stack::Top\">Top</a>",synthetic:false,types:["holochain_wasm_utils::memory::stack::Top"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"holochain_wasm_utils/memory/stack/struct.WasmStack.html\" title=\"struct holochain_wasm_utils::memory::stack::WasmStack\">WasmStack</a>",synthetic:false,types:["holochain_wasm_utils::memory::stack::WasmStack"]},];
implementors["logging"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"logging/color/enum.Color.html\" title=\"enum logging::color::Color\">Color</a>",synthetic:false,types:["logging::color::Color"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"logging/color/struct.ColoredLevelConfig.html\" title=\"struct logging::color::ColoredLevelConfig\">ColoredLevelConfig</a>",synthetic:false,types:["logging::color::ColoredLevelConfig"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
