(function() {var implementors = {};
implementors["hdk"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"hdk/api/struct.DNA_NAME.html\" title=\"struct hdk::api::DNA_NAME\">DNA_NAME</a>",synthetic:false,types:["hdk::api::DNA_NAME"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"hdk/api/struct.DNA_ADDRESS.html\" title=\"struct hdk::api::DNA_ADDRESS\">DNA_ADDRESS</a>",synthetic:false,types:["hdk::api::DNA_ADDRESS"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"hdk/api/struct.AGENT_ID_STR.html\" title=\"struct hdk::api::AGENT_ID_STR\">AGENT_ID_STR</a>",synthetic:false,types:["hdk::api::AGENT_ID_STR"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"hdk/api/struct.AGENT_ADDRESS.html\" title=\"struct hdk::api::AGENT_ADDRESS\">AGENT_ADDRESS</a>",synthetic:false,types:["hdk::api::AGENT_ADDRESS"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"hdk/api/struct.AGENT_INITIAL_HASH.html\" title=\"struct hdk::api::AGENT_INITIAL_HASH\">AGENT_INITIAL_HASH</a>",synthetic:false,types:["hdk::api::AGENT_INITIAL_HASH"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"hdk/api/struct.PUBLIC_TOKEN.html\" title=\"struct hdk::api::PUBLIC_TOKEN\">PUBLIC_TOKEN</a>",synthetic:false,types:["hdk::api::PUBLIC_TOKEN"]},];
implementors["holochain_net"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"holochain_net/tweetlog/struct.TWEETLOG.html\" title=\"struct holochain_net::tweetlog::TWEETLOG\">TWEETLOG</a>",synthetic:false,types:["holochain_net::tweetlog::TWEETLOG"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
