(function() {var implementors = {};
implementors["hdk"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"hdk/api/struct.DNA_NAME.html\" title=\"struct hdk::api::DNA_NAME\">DNA_NAME</a>",synthetic:false,types:["hdk::api::DNA_NAME"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"hdk/api/struct.DNA_HASH.html\" title=\"struct hdk::api::DNA_HASH\">DNA_HASH</a>",synthetic:false,types:["hdk::api::DNA_HASH"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"hdk/api/struct.AGENT_ID_STR.html\" title=\"struct hdk::api::AGENT_ID_STR\">AGENT_ID_STR</a>",synthetic:false,types:["hdk::api::AGENT_ID_STR"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"hdk/api/struct.AGENT_ADDRESS.html\" title=\"struct hdk::api::AGENT_ADDRESS\">AGENT_ADDRESS</a>",synthetic:false,types:["hdk::api::AGENT_ADDRESS"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"hdk/api/struct.AGENT_INITIAL_HASH.html\" title=\"struct hdk::api::AGENT_INITIAL_HASH\">AGENT_INITIAL_HASH</a>",synthetic:false,types:["hdk::api::AGENT_INITIAL_HASH"]},];
implementors["holochain_net_ipc"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"holochain_net_ipc/context/struct.ZMQ_CTX.html\" title=\"struct holochain_net_ipc::context::ZMQ_CTX\">ZMQ_CTX</a>",synthetic:false,types:["holochain_net_ipc::context::ZMQ_CTX"]},];
implementors["holochain_sodium"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"holochain_sodium/secbuf/struct.SecBuf.html\" title=\"struct holochain_sodium::secbuf::SecBuf\">SecBuf</a>",synthetic:false,types:["holochain_sodium::secbuf::SecBuf"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"holochain_sodium/secbuf/struct.Locker.html\" title=\"struct holochain_sodium::secbuf::Locker\">Locker</a>&lt;'a&gt;",synthetic:false,types:["holochain_sodium::secbuf::Locker"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
