name: 'Check spelling'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  spellcheck: # run the action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Get dictionaries'
        run: |
          npm install @cspell/dict-lorem-ipsum
          npm install @cspell/dict-rust
      - uses: streetsidesoftware/cspell-action@v5
        with:
          root: 'src'
          files: '**/*.{json5,njk,md}'
          incremental_files_only: false

  ci_pass:
    if: ${{ always() }}
    runs-on: "ubuntu-latest"
    needs:
      - spellcheck
    steps:
      - name: check status
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
